<a href="https://colab.research.google.com/github/hmzashh/programming-tests/blob/main/problemsolving.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**python practical problem solving




# **List**

In [2]:
#creat a list containing numbers frio 1 to 10 and print only the even number
list1=[1,2,3,4,5,6,7,8,9,10]
for i in list1:
  if i%2==0:
    print(i)

2
4
6
8
10


In [3]:
#write function that takes 2 lists and returns a list of common elements
list1=[1,2,3,4,5,6]
list2=[4,5,6,7,8,9]
for i in list1:
  for j in list2:
    if i==j:
      print(i)

4
5
6


In [5]:
#reverse a list without using reverse or slicing
list1=[5,6,7,4,3,1]
for i in list1:


[1, 3, 4, 7, 6, 5]
[1, 3, 4, 7, 6, 5]
[1, 3, 4, 7, 6, 5]
[1, 3, 4, 7, 6, 5]
[1, 3, 4, 7, 6, 5]
[1, 3, 4, 7, 6, 5]


In [6]:
#calculate the sum of all elements in listwithout using sum()
list1=[1,2,5,4,8,7]
summ=0
for i in list1:
  summ=summ+i
print(summ)


27


In [16]:
#find the second largest number in a list
list1=[9,5,1,5,1,2,3,7]
list1=list(set(list1))
list1.sort(reverse=True)
print(list1)
print(list1[1])

[9, 7, 5, 3, 2, 1]
7


# **Tuple**

In [19]:
#create a tuple with 5 numbers.print the maximum and minimum numbers without using max an min
tup1=(1,2,3,8,7)
maxvalue=i
minvalue=i
for i in tup1:
  if i>maxvalue:
    maxvalue=i
  if i<minvalue:
    minvalue=i
print(maxvalue)
print(minvalue)

8
1


In [30]:
#write a function that swapthe first and last elements of a tuple

tup1=(1,2,3,4,5,6)


def swap(x):
  tup2=list(x)
  print(tup2[-1])
  print(tup2[0])
  a=tup2[-1]
  b=tup2[0]
  tup2[0]=a
  tup2[-1]=b
  tup3=tuple(tup2)
  print(tup3)

swap(tup1)

6
1
(6, 2, 3, 4, 5, 1)


In [39]:
#convert a tuple into a list ,sort it and convertback to tuple
tup1=(1,5,7,4,3,6,9)
a=list(tup1)
print(a)

a.sort()
print(a)

tup1=tuple(a)
print(tup1)

[1, 5, 7, 4, 3, 6, 9]
[1, 3, 4, 5, 6, 7, 9]
(1, 3, 4, 5, 6, 7, 9)


In [83]:
#count how many times an element appears in a tuple
tup1=(1,3,5,5,7,8,5,4,6,4)


for i in tup1:
  cnt=0
  for j in tup1:
    if i==j:
      cnt+=1
  print("numver of", i ,"is" ,cnt)






numver of 1 is 1
numver of 3 is 1
numver of 5 is 3
numver of 5 is 3
numver of 7 is 1
numver of 8 is 1
numver of 5 is 3
numver of 4 is 2
numver of 6 is 1
numver of 4 is 2


# **Dictionary**

In [17]:
#create dic of 5 student with thier grads and print whoes pass
dict1={"ali":55,"alaa":60,"mohd":45,"raad":41,"hmza":65}
print(dict1.values())
for i,j in dict1.items():
  if j>=50:
    print("students that pass exam : ",i)

dict_values([55, 60, 45, 41, 65])
students that pass exam :  ali
students that pass exam :  alaa
students that pass exam :  hmza


In [23]:
#write function that merge 2 dic into 1
dict1={"ali":55,"alaa":60,"mohd":45,"raad":41,"hmza":65}
dict2={"olyan":95,"omar":69,"ahmad":45}

def merge(fdic,sdec):
  fdic.update(sdec)
  return fdic

print(merge(dict1,dict2))

{'ali': 55, 'alaa': 60, 'mohd': 45, 'raad': 41, 'hmza': 65, 'olyan': 95, 'omar': 69, 'ahmad': 45}


In [28]:
#find key with hieghst valuewithout max fun
dict1={"ali":55,"alaa":60,"mohd":45,"raad":91,"hmza":65}
manum=i
for i in dict1.values():
  if i > manum:
    manum=i
print("max num bet va;ues is : ",manum)


max num bet va;ues is :  91


In [65]:
dict1={"ali":55,"alaa":60,"mohd":45,"raad":91,"hmza":65}

for x,y in dict1.items():
  dict1.x=dict1.x

print(dict1)

AttributeError: 'dict' object has no attribute 'x'

In [101]:
dict1={"ali":55,"alaa":60,"mohd":45,"raad":91,"hmza":65}
for x in dict1.keys():

  for z in x:
    cnt=0
    for y in x:

      if y==z:
        cnt+=1
    print(cnt,z)


1 a
1 l
1 i
3 a
1 l
3 a
3 a
1 m
1 o
1 h
1 d
1 r
2 a
2 a
1 d
1 h
1 m
1 z
1 a


# **SET**

In [102]:
#create 2 sets and print union and intersection bet them
set1={1,2,4,"ali"}
set2={2,1,5,"omar"}
z=set1.intersection(set2)
print("intersection is ",z)
y=set1.union(set2)
print("union is ",y)


intersection is  {1, 2}
union is  {1, 2, 'omar', 4, 5, 'ali'}


In [104]:
#remove duplicate from list by converting it to set then back to list
list1=[2,5,5,6,7,7,8,9,9,9]
print("this is list : ",list1)

list2=set(list1)
print("after remove any duplicate value",list2)

this is list :  [2, 5, 5, 6, 7, 7, 8, 9, 9, 9]
after remove any duplicate value {2, 5, 6, 7, 8, 9}


In [108]:
#function to check if 2 set are disjoint
set1={1,2,4,"ali"}
set2={2,1,5,"omar"}

def disjoint(x,y):
  w=x.intersection(y)
  if len(w)==0:
    print("no common elements")
  else:
    print("we have common elements")

disjoint(set1,set2)

we have common elements


In [120]:
#find the symm diff between 2 sets
set1={1,2,4,"ali"}
set2={2,1,5,"omar"}
list1=[]
x=set1.intersection(set2)
print(x)
y=set1.union(set2)
print(y)
for i in y:
  if i not in x:
    list1.append(i)
print(set(list1))




{1, 2}
{1, 2, 'omar', 4, 5, 'ali'}
{'omar', 4, 5, 'ali'}


# **IF CONDITION**

In [127]:
#write programm that checks if a number is +ve,-ve,o
x=0

if x>0:
  print("this number is positive")
elif x<0:
    print("this number is negative")
else:
  print("this number is zero")

this number is zero


In [133]:
#function to check leap year
x=input("insert year")
x=int(x)
def leapyear(x):
  if x%4==0 and x%100!=0:
    print("this is leap year")
  else:
    print("this is not leap year")
leapyear(x)


insert year2020
this is leap year


In [136]:
#program to check if a char is vowel or constant
sttr="hmza alshehab"
ela="aeiou"
for i in sttr:
  if i in ela:
    print("this char ",i,"is vowel")
  else:
    print("this char ",i,"is constant")


this char  h is constant
this char  m is constant
this char  z is constant
this char  a is vowel
this char    is constant
this char  a is vowel
this char  l is constant
this char  s is constant
this char  h is constant
this char  e is vowel
this char  h is constant
this char  a is vowel
this char  b is constant


# **WHILE loop**

In [155]:
#prog to print numbers from 1 to 100 and stop if number divisable by 17
i=1
while i <100:
  if i % 17==0:
    break

  print(i)
  i+=1


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [169]:
x = input("insert number")
list1 = []
while x != '-1':
    x_int = int(x)
    list1.append(x_int)
    x = input("insert number")
print("sum is :",sum(list1))


insert number-1
sum is : 0


In [173]:
i=1
while i <=50:
  if i % 2 !=0:
    print("this number is odd :",i)
  i+=1


this number is odd : 1
this number is odd : 3
this number is odd : 5
this number is odd : 7
this number is odd : 9
this number is odd : 11
this number is odd : 13
this number is odd : 15
this number is odd : 17
this number is odd : 19
this number is odd : 21
this number is odd : 23
this number is odd : 25
this number is odd : 27
this number is odd : 29
this number is odd : 31
this number is odd : 33
this number is odd : 35
this number is odd : 37
this number is odd : 39
this number is odd : 41
this number is odd : 43
this number is odd : 45
this number is odd : 47
this number is odd : 49


# **FOR loop**

In [180]:
#print the multiplication table from 1 to 10 for given number
x=int(input("insert number"))

for i in range(10):
  mul=x*i
  print(x," * " ,i, "is : " ,mul)

insert number5
5  *  0 is :  0
5  *  1 is :  5
5  *  2 is :  10
5  *  3 is :  15
5  *  4 is :  20
5  *  5 is :  25
5  *  6 is :  30
5  *  7 is :  35
5  *  8 is :  40
5  *  9 is :  45


In [185]:
#count the vowels number of given string
str1="hmza alshehab"
vowel="aeiou"
cnt=0
for i in str1:
  if i in vowel:
    cnt+=1
print("the number of vowel char in given string is : ",cnt)

the number of vowel char in given string is :  4


In [188]:
#loop to list and print elements greater than 5
list1=[5,8,7,3,6,88,7]
for i in list1:
  if i> 5:
    print(i)

8
7
6
88
7


# **Function**

In [16]:
#factorial
def factor(n):
  result = 1
  for i in range(2, n + 1):
    result *= i
  return result
num = 9
print("Factorial is:", factor(num))


Factorial is: 362880


In [13]:
#palindrome
str1="solos"
def palind(str1):
  str2=""

  for i in range(len(str1)-1,-1,-1):
    str2+=str1[i]
  print(str2)
  if str2==str1:
    print("palindrome")
  else:
    print("not palindrome")


palind(str1)


solos
palindrome


In [23]:
#squares list item
from math import sqrt

list1 = [1, 2, 3, 4, 5, 6]
print(list1)
def seq(list1):
  list2=[]
  for i in list1:
    new=(i**2)
    list2.append(new)
  print(list2)

seq(list1)

[1, 2, 3, 4, 5, 6]
[1, 4, 9, 16, 25, 36]


# **recursion**

In [26]:
def fibon(n):

  if n <= 1:
    return n
  else:
    return fibon(n-1) + fibon(n-2)

print(fibon(10))


55


In [33]:
def poe(x,n):
  if n==0:
    return 1
  else:
    return x*(poe(x,n-1))
print(poe(3,2))

9


In [2]:
list1=[1,2,3,4,5]
def summ(list1):
  if len(list1)==0:
    return 0
  else:
    return list1[0]+summ(list1[1:])

print(summ(list1))


15


# **Break and continue**

In [5]:
#loop print 1 to 20 but skip mul of 3
for i in range(1,20):
  if i%3==0:
    continue

  print(i)

1
2
4
5
7
8
10
11
13
14
16
17
19


In [10]:
#loop print from 1 to 50 and breaks loop if num divisible by 13 and 7
for i in range(1, 50):
    if (i % 7 == 0) and (i % 13 == 0):
        break
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90


In [11]:
#for loop that breaks when it find the first even num in list
list1=[1,5,6,8,7]
for i in list1:
  if i%2==0:
    break
  print(i)

1
5


# **lambda**

In [18]:
#sort list of tup based on second element
list1=[(2,4),(3,9),(8,4)]
sort_list=sorted(list1,key=lambda l:l[1] )
print(sort_list)

[(2, 4), (8, 4), (3, 9)]


In [15]:
#write lambda function that return squre of number

seq=lambda x:x**2
print(seq(3))

9


In [20]:
#filter out even number from list using filter and lambda function
list1=[2,1,4,5,6,7]
even=list(filter(lambda x:x%2==0,list1))
print(list(even))


[2, 4, 6]


# **OOP**

In [26]:
#create car class with (brand,model)
class car:
  def __init__(self,brand,model):
    self.brand=brand
    self.model=model
  def car_details(self):
    print("car details : ",self.brand,self.model)

a=car("changan",2025)
a.car_details()

car details :  changan 2025


In [34]:
#create parent and child classes that inherent annd add new methode
class parent:
  def __init__(self,name,birthday):
    self.name=name
    self.birthday=birthday

  def full_det(self):
    print("details : ",self.name,self.birthday)

class child(parent):
  def __init__(self,x,y):
    super().__init__(x,y)
    self.x=x
    self.y=y
  def nam(self):
    print("only name",self.x)

a=child("ali",1999)
a.nam()
a.full_det()

only name ali
details :  ali 1999


In [38]:
#write 2 classes dog and cat that both have method make_sound then call make sound ,using polyporphic
class animal:
  def __init__(self,animal,sound):
    self.animal=animal
    self.sound=sound
  def make_sound(self):
    print(self.sound)

class dog(animal):
  def make_sound(self):
    print("dog sound",self.sound)
class cat(animal):
  def make_sound(self):
    print("cat sound",self.sound)

a=dog("dog","bark")
a.make_sound()

b=cat("cat ","meo")
b.make_sound()

dog sound bark
cat sound meo


In [18]:
#class method
class car:
    count = 0
    def __init__(self):
        car.count += 1

    @classmethod
    def get_count(cls):
        return cls.count

c1 = car()
c2 = car()
print(car.get_count())


2


In [47]:
#abstract
from abc import ABC, abstractmethod

class shape(ABC):
  @abstractmethod

  def area():
    pass
class rect(shape):
  def __init__(self,x,y):
    self.x=x
    self.y=y

  def area(self):
    area=self.x*self.y
    return area

class cir(shape):
  def __init__(self,x):
    self.x=x

  def area(self):
    area=3.14*(self.x**2)
    return area

rec=rect(4,5)
print(rec.area())

circ=cir(5)
print(circ.area())





20
78.5


In [55]:
#class with private attribute ,getter and setter
class hmza:
  def __init__(self,name,salary):
    self.name=name
    self.__salary=salary
  def get_salary(self):
    return self.__salary

  def set_salary(self,val):
    self.__salary+=val

a=hmza("ali",600)
print(a.get_salary())
a.set_salary(5)
print(a.get_salary())

600
605


# **JSON**

In [57]:
#convert dic to json
data_dic={"name":"ali","age":24,"city":"amman"}
jso_data=json.dumps(data_dic)
print(jso_data)

{"name": "ali", "age": 24, "city": "amman"}


In [56]:
#read data from json file and print it
import json
json_data='{"name":"ali","age":24,"city":"amman"}'
data_dict=json.loads(json_data)
print(data_dict)

{'name': 'ali', 'age': 24, 'city': 'amman'}


In [ ]:
#write python object into json file
data_dic={"name":"ali","age":24,"city":"amman"}
jso_data=json.dumps(data_dic)
print(jso_data)

# **numpy**

In [61]:
#create 2d numpy array of zeros
import numpy as np
arr1=np.array([[0,0,0],[0,0,0]])
print(arr1)
print(arr1.ndim)

[[0 0 0]
 [0 0 0]]
2


In [62]:
#1D numpy array of 10 rendom int bet 1 to 100
import numpy as np
randarr=np.random.randint(1,100,10)
print(randarr)

[57 84 84 83 95 98 47 17 86 92]


In [66]:
#maen ,median and std for numpy array
import numpy as np
arr1=np.array([1,2,4,5,7,8,9])
print(arr1.mean())
print(np.median(arr1))
print(arr1.std())

5.142857142857143
5.0
2.799416848895061


In [70]:
#reshape to 2 D
import numpy as np
arr1=np.array([1,2,4,5,7,8])
print(arr1.shape)
print(arr1.reshape(2,3))

(6,)
[[1 2 4]
 [5 7 8]]


In [1]:
#element wise addition
import numpy as np
arr1=np.array([1,2,4,5,7,8])
arr2=np.array([1,6,8,1,7,10])
np.add(arr1,arr2)


array([ 2,  8, 12,  6, 14, 18])

In [3]:
#matrix mul
import numpy as np
arr1=np.array([[2,4,6],[8,10,12]])
arr2=np.array([[7, 8],
              [9, 10],
              [11, 12]])

result = np.dot(arr1, arr2)
print(result)

[[116 128]
 [278 308]]


In [6]:
#find max and min valurs and their indices
arr1=np.array([[2,4,6],[8,10,12]])
print(np.max(arr1))
print(np.argmax(arr1))
print(np.min(arr1))
print(np.argmin(arr1))

12
5
2
0


In [17]:
#slice nupy array to get only 3 rows,and 2 column
import numpy as np
arr1=np.array([[2,4,5],
       [5,6,7],
       [3,2,9],[8,4,6]])

print(arr1[:3,:2])

[[2 4]
 [5 6]
 [3 2]]
